### 1. words_list 라는 list 안에 love, hate, I, happy, you, am, birthday, to, from, for, me, **dog** 라는 단어가 차례로 포함되어 있다. 이 단어들을 조합하여 2개의 문장을 만드시오.

In [4]:
words_list = ['love','hate','I','happy','you','am','birthday','to','from','me','dog']
print(words_list[2]+" "+words_list[0]+ " "+words_list[4])
print(words_list[3]+" "+words_list[6]+ " " +words_list[7] +" " +words_list[4])

I love you
happy birthday to you

### 2. 어느 카페의 메뉴가 4가지 있다. Americano, Cafe latte, Green tea latte, Cafe mocha 각 메뉴의 가격은 3000원, 4000원, 4500원, 5000원일 때, 이 메뉴 목록을 dictionary로 작성하고 Cafe latte와 Cafe mocha 를 주문했을 때 결제액을 계산하는 프로그램을 작성하시오.

In [16]:
menu = {'Americano': 3000, 'Cafe latte': 4000, 'Green tea latte': 4500 ,'Cafe mocha' : 5000}
print(menu['Cafe latte']+menu['Cafe mocha'])

9000

### 3. 리스트를 원소로 갖는 리스트의 각 원소들의 합을 구하는 프로그램을 작성하시오.

a = [(1,2), (3,4),(6,7),(10,11)]

(hint) for (n1,n2) in a:

In [45]:
a = [(1,2), (3,4),(6,7),(10,11)]
sum = 0
for i in a:
  for j in i:
    sum += j

print(sum)

44

### 4. 10~30 사이의 홀수를 출력하는 프로그램을 작성하시오.

In [ ]:
for i in range(10,30):
  if(i%2!=0):
    print(i)

11
13
15
17
19
21
23
25
27
29

### 5. 2020년이 윤년인지 검사하는 프로그램을 작성하시오.


*  400 으로 나누어 떨어지는 해는 윤년이다.
*  4로 나누어 떨어지는 해는 윤년이다.
*  4로 나누어 떨어지지만 100으로 나누어 떨어지는 해는 윤년이 아니다.

In [59]:
a = int(input("연도를 입력하시오 :"))

if (a % 400 == 0) or ((a % 4 == 0) and (a % 100 != 0)):
    print("윤년이다.")
else:
    print("윤년이 아니다.")

연도를 입력하시오 :2002
윤년이 아니다.